name: Shell commands

on:
  push:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Hello github actions" > myfile.txt
      - name: Multiline script
        run: |
          node -v
          npm -v
          cat myfile.txt
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: myfile.txt

  build-with-maven:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Built with maven
        run: mvn clean package
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/*.jar

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [build-with-maven]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar-file
      - name: check content
        run: |
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE