name: Shell commands

on:
  push:
    branches:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Hello github actions" > myfile.txt
      - name: Multiline script
        run: |
          node -v
          npm -v
          cat myfile.txt
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: myfile.txt

  run-another-shell-command:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Built with maven
        run: mvn clean package
      - name: Show result
        run: |
          ls
          cd target
          ls